run:
  timeout: 5m
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gosimple:
    checks: ["all"]
  govet:
    enable-all: true
    disable:
      - fieldalignment  # Memory optimization suggestions, not critical for test code
  shadow:
    enabled: true
  ineffassign:
    check-return-statements: true
  staticcheck:
    checks: ["all"]
  unused:
    check-exported: false
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 15

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - whitespace
  disable:
    - typecheck  # Already done by go build

issues:
  exclude-dirs:
    - vendor
  exclude-files:
    - ".*\\.s$"  # Exclude assembly files
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
        - gocyclo  # Test functions often have high complexity due to multiple test cases
    - path: ".*\\.s$"  # Exclude assembly files from all linters
      linters:
        - all
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number

